name: Demo Workflow
run-name: Demo Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Create Hello.txt
        run: echo "Hello, World!" > Hello.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: ./Hello.txt
  echo:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Hello
      - name: Print Hello
        run: cat Hello.txt
